version: '3.8'

services:
  app:
    build: .
    container_name: studysync-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/studysync?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-256-bit-secret-key-for-development-only-change-in-production
    depends_on:
      - mongodb
      - redis
    networks:
      - studysync-network
    restart: unless-stopped
    
  mongodb:
    image: mongo:7.0
    container_name: studysync-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=studysync
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - studysync-network
    restart: unless-stopped
      
  redis:
    image: redis:7.2-alpine
    container_name: studysync-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - studysync-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    
  nginx:
    image: nginx:alpine
    container_name: studysync-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - studysync-network
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:

networks:
  studysync-network:
    driver: bridge



