version: '3.8'

services:
  # Simple StudySync API
  studysync-api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: studysync-api
    ports:
      - "8080:8080"
    networks:
      - studysync-network
    restart: unless-stopped
    
  # MongoDB for data storage
  mongodb:
    image: mongo:7.0
    container_name: studysync-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=studysync
    volumes:
      - mongodb_data:/data/db
    networks:
      - studysync-network
    restart: unless-stopped
      
  # Redis for caching
  redis:
    image: redis:7.2-alpine
    container_name: studysync-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - studysync-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    
  # MongoDB Admin Interface (optional)
  mongo-express:
    image: mongo-express:latest
    container_name: studysync-mongo-admin
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - studysync-network
    restart: unless-stopped

volumes:
  mongodb_data:
  redis_data:

networks:
  studysync-network:
    driver: bridge

