spring:
  application:
    name: StudySync
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/studysync}
      auto-index-creation: true
    
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        max-wait: -1ms
  
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
  
  security:
    jwt:
      secret: ${JWT_SECRET:your-256-bit-secret-key-for-development-only-change-in-production}
      access-token-expiration: 900000     # 15 minutes
      refresh-token-expiration: 2592000000 # 30 days

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.studysync: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

studysync:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8081
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
  
  rate-limiting:
    enabled: true
    default-limit: 100
    default-duration: 60000
  
  anti-cheat:
    max-session-duration: 14400  # 4 hours in seconds
    anomaly-threshold: 0.7
    suspicious-patterns-enabled: true
  
  websocket:
    endpoint: /ws
    allowed-origins: "*"



